%Signed Resistence Distance

edges = load('Data\Alpha\seed=6\train_edges.txt');
sources = edges(:, 1) + 1;  % Edge list is generated by Py script, such that index starts from 0.
targets = edges(:, 2) + 1;
weights = edges(:, 3);
G = graph();  % Undirected Graph
G = addedge(G, sources, targets, weights);
G = simplify(G);  % Delete repeated edges
numNodes = G.numnodes;

A = full(adjacency(G,'weighted'));
I = speye(numNodes);
vecD = abs(A) * ones(numNodes, 1);
D = speye(numNodes);
for i = 1: numNodes
    D(i, i) = vecD(i);
end
L = D - A;
invL = inv(L);

d = 32;
[U, S, V] = svds(invL, d);
S = inv(S);
emb = U * (S ^ (1/2));
save('C:\Users\wenbin\Desktop\emb', 'emb');
